### PR TITLE
Using placeholder for items without image

### LINKED ISSUE #2: #INC-5312: Missing image
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

### PR DESCRIPTION
**Pull request by leonliman**
Fixes #2 

# Description

Used placeholder.png when no image is specified while creating a new item (looks like on the attached image)
Bildschirmfoto 2022-07-25 um 15 45 15

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @leonliman, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Comment by leonliman** [comment]
They are fixed now

**Review by leonliman — COMMENTED** [review]
ok

**Pull request closed without merging**
